return {
  api = require "utils.api",
  array = require "utils.array",
  buf = require "utils.buf",
  cmd = require "utils.cmd",
  complete = require "utils.complete",
  encoding = require "utils.encoding",
  flag = require "utils.flag",
  http = require "utils.http",
  lmstudio = require "utils.lmstudio",
  os = require "utils.os",
  range = require "utils.range",
  sway = require "utils.sway",
  table = require "utils.table",
  time = require "utils.time",
  utf8 = require "utils.utf8",
}
